### ISSUE TITLE
Dependency incompatibility

### ISSUE THREAD

**Issue by connorhsm** [OpenGovAus/legistream-site#20]
> requests 2.25.1 requires idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.

It's possible this repo doesn't directly require these instead they're required by our dependencies, it may be a good idea to review dependencies and possibility consider [python-poetry.org/](http://python-poetry.org/) over virtualenv/pip.

**Comment by king-millez** [comment]
Poetry is worth a look, I think those modules are required by `legistream-backend`, but `pip` doesn't install them properly so I just made them dependencies for the site which works fine.
